name: "saritasa-s3-tools"

volumes:
  rustfs_data:

services:
  # ###########################################################################
  # RustFS Storage
  # rustfs:9000 - Server
  # rustfs:9001 - UI
  # ###########################################################################
  rustfs:
    image: rustfs/rustfs:latest
    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=rootroot
      - RUSTFS_CONSOLE_ENABLE=true
      # Set `RUSTFS_SERVER_DOMAINS` to enable virtual-hosted-style for rustfs.
      # https://docs.rustfs.com/en/integration/virtual
      - RUSTFS_SERVER_DOMAINS=s3.rustfs.localhost
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
    networks:
      default:
        aliases:
          # Set alias that suitable for virtual-hosted-style URL structure:
          # `https://<bucket>.s3.<region>.amazonaws.com/<key>
          # We need apply this style for local S3 storage because path-style
          # URLs will be discontinued in the future, and we want to make
          # consistent URLs for uploading and downloading files.
          # https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
          - ${COMPOSE_PROJECT_NAME}-files.s3.rustfs.localhost
    healthcheck:
      test: curl -f http://127.0.0.1:9001/health/ready
      interval: 0.1s
      timeout: 3s
      retries: 30

  # ###########################################################################
  # Service for creating bucket in rustfs service
  # ###########################################################################
  rustfs-create-bucket:
    image: rustfs/rc:latest
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/rc alias set local http://rustfs:9000 root rootroot;
      /usr/bin/rc bucket create --ignore-existing local/${COMPOSE_PROJECT_NAME}-files;
      /usr/bin/rc anonymous set public local/${COMPOSE_PROJECT_NAME}-files;
      exit 0;
      "

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME} || false"
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD=postgres
